=== eGangotri/indicTools/xml/dictionary.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>
<!ELEMENT em (#PCDATA)>
<!ELEMENT entry (word,meaning+)>
<!ELEMENT li (em)>
<!ELEMENT meaning (#PCDATA|a|em|ol|strong)*>
<!ELEMENT ol (li)>
<!ELEMENT root (entry+)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT word (#PCDATA)>

=== eGangotri/indicTools/xml/jj.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "dictionary.dtd">
<root>

<entry>
<word>
ña 1</word>


<meaning>
{ña} the palatal nasal (found before palatal consonants)
</meaning>


</entry>

<entry>
<word>
 ñakāra </word>


<meaning>
{kāra} m. the letter {ñ}
</meaning>


</entry>

<entry>
<word>
ña 2</word>


<meaning>
{ña} m. a singer <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a jingling sound <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a heretic <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 an ox <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 the planet Śukra <a href="/html/abbreviations.html#L">L.</a>
</meaning>


</entry>

<entry>
<word>
 </word>


<meaning>
{}
</meaning>


</entry>

</root>

=== eGangotri/indicTools/xml/tth.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "dictionary.dtd">
<root>

<entry>
<word>
ṭha 1</word>


<meaning>
{ṭha} the aspirate of the preceding consonant
</meaning>


</entry>

<entry>
<word>
 ṭhakāra </word>


<meaning>
{kāra} m. the letter {ṭh} <a href="/html/abbreviations.html#Pāṇ">Pāṇ.</a> 8-4, 41 <a href="/html/abbreviations.html#Kāś">Kāś.</a> 
</meaning>


<meaning>
 {raya} Nom. (Desid. {ṭiṭh"ṣ "ṣyiṣatī}), 54 <a href="/html/abbreviations.html#Kāś">Kāś.</a>
</meaning>


</entry>

<entry>
<word>
ṭha 2</word>


<meaning>
{ṭha} m. a loud noise ({ṭhaṭhaṃ ṭhaṭhaṃ ṭhaṃ ṭhaṭhaṭhaṃ ṭhaṭhaṃ ṭhaḥ}, an imitative sound as of a golden pitcher rolling down steps <a href="/html/abbreviations.html#Mahān">Mahān.</a>2 iii, 5) <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 the moon's disk <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a disk <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a cypher <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a place frequented by all <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 Śiva <a href="/html/abbreviations.html#L">L.</a>
</meaning>


</entry>

<entry>
<word>
ṭhaṃsarī </word>


<meaning>
{ṭhaṃsarī} f. N. of a stringed instrument
</meaning>


</entry>

<entry>
<word>
ṭhakka </word>


<meaning>
{ṭhakka} m. a merchant (= {ṭakka}) <a href="/html/abbreviations.html#Inscr">Inscr.</a> (Ist century AḌ.)
</meaning>


</entry>

<entry>
<word>
ṭhakkana </word>


<meaning>
{ṭhakkana} m. N. of a prince <a href="/html/abbreviations.html#Rājat">Rājat.</a> vi, 230ff. and 236 (vv.Il. {ḍkakk}, {thakk})
</meaning>


</entry>

<entry>
<word>
ṭhakkura </word>


<meaning>
{ṭhakkura} m. a deity, object of reverence, man of rank, chief (the modern 'Thākūr, Tagore' added to names), vii f. <a href="/html/abbreviations.html#Dhūrtas">Dhūrtas.</a> i, . 19/20
</meaning>


</entry>

<entry>
<word>
ṭhaṭhaṃ </word>


<meaning>
{ṭhaṭhaṃ} {ṭhaṭhaṭhaṃ}, See 2. {ṭha}
</meaning>


</entry>

<entry>
<word>
ṭhātkāra </word>


<meaning>
{ṭhāt-kāra} m. = {ṭāṃ-k} <a href="/html/abbreviations.html#Bālar">Bālar.</a> iii
</meaning>


</entry>

<entry>
<word>
ṭhāra </word>


<meaning>
{ṭhāra} rime <a href="/html/abbreviations.html#KātyŚr">KātyŚr.</a> xv, 4, 38 <a href="/html/abbreviations.html#Sch">Sch.</a>
</meaning>


</entry>

<entry>
<word>
ṭhiṇṭhā </word>


<meaning>
{ṭhiṇṭhā} f. a gaming-house <a href="/html/abbreviations.html#Kathās">Kathās.</a> xcī, 15 and 21 ({ṭiṇ}), cxxiv, 211 
</meaning>


<meaning>
 N. of a woman <a href="/html/abbreviations.html#Rājat">Rājat.</a> vii, 103
</meaning>


</entry>

<entry>
<word>
 ṭhiṇṭhākarāla </word>


<meaning>
{karāla} m. N. of a gaming-house keeper <a href="/html/abbreviations.html#Kathās">Kathās.</a> cxxi, 71f
</meaning>


</entry>

<entry>
<word>
ṭhetkṛta </word>


<meaning>
{ṭhet-kṛta} n. the roaring (of a bull) <a href="/html/abbreviations.html#Alaṃkārat">Alaṃkārat.</a>
</meaning>


</entry>

<entry>
<word>
ṭhoṇṭhapaddhahati </word>


<meaning>
{ṭhoṇṭha-paddhahati} f. N. of wk., Śūdradh.
</meaning>


</entry>

<entry>
<word>
 </word>


<meaning>
{}
</meaning>


</entry>

</root>

=== eGangotri/indicTools/xml/gg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "dictionary.dtd">
<root>

<entry>
<word>
ṅa 1</word>


<meaning>
{ṅa} the 5th consonant of the Sanskṛit alphabet, nasal of the 1st class. No word in use begins with this letter 
</meaning>


<meaning>
 it is usually found as the 1st member of a conjunct consonant preceded by a vowel
</meaning>


</entry>

<entry>
<word>
 ṅakāra </word>


<meaning>
{kāra} m. the letter or sound {ṅa}
</meaning>


</entry>

<entry>
<word>
ṅa 2</word>


<meaning>
{ṅa} m. an object of sense <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 desire for any sensual object <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 Śiva ({bhairava}) <a href="/html/abbreviations.html#L">L.</a>
</meaning>


</entry>

<entry>
<word>
ṅu </word>


<meaning>
{ṅu} cl. 1. Ā. {ṅavate}, to sound <a href="/html/abbreviations.html#Dhātup">Dhātup.</a> xxii, 57: Desid. {ñuṇūṣate} <a href="/html/abbreviations.html#Pāṇ">Pāṇ.</a> 7-4, 62 <a href="/html/abbreviations.html#Sch">Sch.</a>
</meaning>


</entry>

<entry>
<word>
 </word>


<meaning>
{}
</meaning>


</entry>

</root>

=== eGangotri/indicTools/xml/th.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "dictionary.dtd">
<root>

<entry>
<word>
tha 1</word>


<meaning>
{tha} aspirate of the preceding letter
</meaning>


</entry>

<entry>
<word>
 thakāra </word>


<meaning>
{kāra} m. the letter or sound {th}
</meaning>


</entry>

<entry>
<word>
 tha 2</word>


<meaning>
{tha} m. a mountain <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a protector <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a sign of danger <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 N. of a disease <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 eating <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 n. preservation <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 fear <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 an auspicious prayer <a href="/html/abbreviations.html#L">L.</a>
</meaning>


</entry>

<entry>
<word>
thakkana </word>


<meaning>
{thakkana} m. {ṭhakk} <a href="/html/abbreviations.html#Rājat">Rājat.</a>
</meaning>


</entry>

<entry>
<word>
thakriya </word>


<meaning>
{thakriya} m. N. of a man, iv, 493
</meaning>


</entry>

<entry>
<word>
thakviyaka </word>


<meaning>
{thakviyaka} N. of a man, v, 151
</meaning>


</entry>

<entry>
<word>
tharatharāya </word>


<meaning>
{tharatharāya} Nom. Ā. (p. {yamāna}) to grow giddy, tumble, Kārāṇḍ. xi, 130
</meaning>


</entry>

<entry>
<word>
tharv </word>


<meaning>
{tharv} cl. 1. P. to go <a href="/html/abbreviations.html#Nir">Nir.</a> xi, 18
</meaning>


</entry>

<entry>
<word>
thalyoraka </word>


<meaning>
{thalyoraka} N. of a village <a href="/html/abbreviations.html#Rājat">Rājat.</a>
</meaning>


</entry>

<entry>
<word>
thuḍ </word>


<meaning>
{thuḍ} cl. 6. {ḍati}, to cover <a href="/html/abbreviations.html#Dhātup">Dhātup.</a>
</meaning>


</entry>

<entry>
<word>
thutkāra </word>


<meaning>
{thut-kāra} m. = {thūt-k} <a href="/html/abbreviations.html#W">W.</a>
</meaning>


</entry>

<entry>
<word>
 thutthukāraka </word>


<meaning>
{thutthu-kāraka} mfn. one who smacks his lips in eating (not admitted into the <a href="/html/abbreviations.html#Buddh">Buddh.</a> brotherhood) <a href="/html/abbreviations.html#L">L.</a>
</meaning>


</entry>

<entry>
<word>
 thuthu </word>


<meaning>
{thuthu} = {thūthū}
</meaning>


</entry>

<entry>
<word>
 thuthukṛt </word>


<meaning>
{kṛt} m. N. of a bird <a href="/html/abbreviations.html#Npr">Npr.</a>
</meaning>


</entry>

<entry>
<word>
thurv </word>


<meaning>
{thurv} cl. 1. p. {thūrvat}, (Agni) hurting (cf. Dhātup. xv, 62 
</meaning>


<meaning>
 <a href="/html/abbreviations.html#√">√.</a>{turv}) <a href="/html/abbreviations.html#MaitrS">MaitrS.</a> ii, 10, 1
</meaning>


</entry>

<entry>
<word>
thūt </word>


<meaning>
{thūt} ind. (fr. {ṣṭhyūta} ?)
</meaning>


</entry>

<entry>
<word>
 thūtkāra </word>


<meaning>
{kāra} m. the sound made in spitting <a href="/html/abbreviations.html#Rājat">Rājat.</a> vii f
</meaning>


</entry>

<entry>
<word>
 thūtkṛta </word>


<meaning>
{kṛta} n. id., vii, 1116
</meaning>


</entry>

<entry>
<word>
 thūtkṛtya </word>


<meaning>
{kṛtya} ind. spitting <a href="/html/abbreviations.html#ib">ib.</a> 

</meaning>


</entry>

<entry>
<word>
 thūthū </word>


<meaning>
{thūthū} imitative sound of spitting, Sûktik
</meaning>


</entry>

<entry>
<word>
thaithai </word>


<meaning>
{thaithai} (in music) imitative sound of a musical instrument
</meaning>


</entry>

<entry>
<word>
thoḍana </word>


<meaning>
{thoḍana} n. fr. √{thuḍ} <a href="/html/abbreviations.html#W">W.</a>
</meaning>


</entry>

<entry>
<word>
thauṇeya </word>


<meaning>
{thauṇeya} {yaka} n. = {sth} <a href="/html/abbreviations.html#Car">Car.</a> vi f
</meaning>


</entry>

<entry>
<word>
 </word>


<meaning>
{}
</meaning>


</entry>

</root>

=== eGangotri/indicTools/xml/lR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "dictionary.dtd">
<root>

<entry>
<word>
ḷ 1</word>


<meaning>
{ḷ} the ninth vowel of the alphabet (resembling the sound {lry} in {revelry} 
</meaning>


<meaning>
 it only appears in some forms of √{kḷp})
</meaning>


</entry>

<entry>
<word>
 ḷkāra </word>


<meaning>
{kāra}
</meaning>


</entry>

<entry>
<word>
 ḷvarṇa </word>


<meaning>
{varṇa} m. the sound {ḷ} <a href="/html/abbreviations.html#RPrāt">RPrāt.</a> <a href="/html/abbreviations.html#APrāt">APrāt.</a> <a href="/html/abbreviations.html#TPrāt">TPrāt.</a>
</meaning>


</entry>

<entry>
<word>
ḷ 2</word>


<meaning>
{ḷ} {ḷs} m. a mountain <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 the earth, the mother of the gods <a href="/html/abbreviations.html#L">L.</a>
</meaning>


</entry>

<entry>
<word>
ḷtaka </word>


<meaning>
{ḷtaka} {as} m. N. of a man, mispronunciation of Ṛitaka <a href="/html/abbreviations.html#Pat">Pat.</a> and <a href="/html/abbreviations.html#Kāś">Kāś.</a> on Śivasūtra 2
</meaning>


</entry>

<entry>
<word>
 </word>


<meaning>
{}
</meaning>


</entry>

</root>

=== eGangotri/indicTools/xml/nn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "dictionary.dtd">
<root>

<entry>
<word>
ṇa 1</word>


<meaning>
{ṇa} the cerebral nasal <a href="/html/abbreviations.html#TPrāt">TPrāt.</a> xxi, 14
</meaning>


</entry>

<entry>
<word>
 ṇakāra </word>


<meaning>
{kāra} m. the letter or sound {ṇ}, vii, 1 ; xiii, 6
</meaning>


</entry>

<entry>
<word>
ṇa 2</word>


<meaning>
{ṇa} m. knowledge <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 certainty, ascertainment <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 ornament <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a water-house <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 = {nirvṛti} (invented for the etymology of {kriṣṇa},) <a href="/html/abbreviations.html#MBh">MBh.</a> v, 70, 5 <a href="/html/abbreviations.html#Sch">Sch.</a> 
</meaning>


<meaning>
 a bad man <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 N. of Śiva or of a <a href="/html/abbreviations.html#Buddh">Buddh.</a> deity <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 the sound of negation <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 gift <a href="/html/abbreviations.html#L">L.</a>
</meaning>


</entry>

<entry>
<word>
ṇya </word>


<meaning>
{ṇya} m. (etymological) N. of an ocean in the Brahma-loka <a href="/html/abbreviations.html#ChUp">ChUp.</a> viii, 5, 3
</meaning>


</entry>

<entry>
<word>
 </word>


<meaning>
{}
</meaning>


</entry>

</root>

=== eGangotri/indicTools/xml/lRR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "dictionary.dtd">
<root>

<entry>
<word>
&#x1e39; 1</word>


<meaning>
{&#x1e39;} the tenth vowel of the alphabet (the corresponding long vowel to {ḷ}, entirely artificial and only appearing in the works of some grammarians and lexicographers)
</meaning>


</entry>

<entry>
<word>
&#x1e39; 2</word>


<meaning>
{&#x1e39;} {&#x1e39;s} m. Śiva <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 f. the mother of the cow of plenty 
</meaning>


<meaning>
 the mother of the Dānavas 
</meaning>


<meaning>
 wife of a Daitya 
</meaning>


<meaning>
 mother 
</meaning>


<meaning>
 divine female 
</meaning>


<meaning>
 female nature
</meaning>


</entry>

<entry>
<word>
 </word>


<meaning>
{}
</meaning>


</entry>

</root>

=== eGangotri/indicTools/xml/ddh.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "dictionary.dtd">
<root>

<entry>
<word>
ḍha 1</word>


<meaning>
{ḍha} the aspirate of the preceding letter,
</meaning>


</entry>

<entry>
<word>
 ḍhakāra </word>


<meaning>
{kāra} m- the letter {ḍh}
</meaning>


</entry>

<entry>
<word>
ḍha 2</word>


<meaning>
{ḍha} mfn. = {nir-guṇa} <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 m. an imitative sound <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a large drum <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a dog <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a dog's tail <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a serpent <a href="/html/abbreviations.html#W">W.</a>
</meaning>


</entry>

<entry>
<word>
ḍhakka </word>


<meaning>
{ḍhakka} m. a large sacred building <a href="/html/abbreviations.html#Rājat">Rājat.</a> iii, v 
</meaning>


<meaning>
 N. of a locality (cf. {ṭakka}) <a href="/html/abbreviations.html#Mricch">Mricch.</a> <a href="/html/abbreviations.html#Sch">Sch.</a> Introd 
</meaning>


<meaning>
 ({ā}), f. a large drum (cf. {gaja-}, {jaya-}) <a href="/html/abbreviations.html#Rājat">Rājat.</a> vi, 133 
</meaning>


<meaning>
 covering, disappearance, W:
</meaning>


</entry>

<entry>
<word>
 ḍhakkadesīya </word>


<meaning>
{"ṣdesīya} mfn. spoken in the district of Ḍhakkia <a href="/html/abbreviations.html#Mṛicch">Mṛicch.</a> <a href="/html/abbreviations.html#Sch">Sch.</a> Introd
</meaning>


</entry>

<entry>
<word>
ḍhakkana </word>


<meaning>
{ḍhakkana} n. shutting (of a door) <a href="/html/abbreviations.html#Śīl">Śīl.</a> 
</meaning>


<meaning>
 m. N. of a man <a href="/html/abbreviations.html#Rājat">Rājat.</a> vi, 230f. (v. l. {kkama})
</meaning>


</entry>

<entry>
<word>
ḍhakkārī </word>


<meaning>
{ḍhakkārī} f. N. of the goddess Tārā or TariṇI, Kulasadbh
</meaning>


</entry>

<entry>
<word>
ḍhaṅka </word>


<meaning>
{ḍhaṅka} m. N. of a mountain <a href="/html/abbreviations.html#Śatr">Śatr.</a> i
</meaning>


</entry>

<entry>
<word>
ḍhaḍḍhara </word>


<meaning>
{ḍhaḍḍhara} N. of a man <a href="/html/abbreviations.html#HPariś">HPariś.</a> . xiii
</meaning>


</entry>

<entry>
<word>
ḍhaṇṭī </word>


<meaning>
{ḍhaṇṭī} f. = {vākya-viśeṣa} <a href="/html/abbreviations.html#Rudray">Rudray.</a>
</meaning>


</entry>

<entry>
<word>
ḍhāmarā </word>


<meaning>
{ḍhāmarā} f. a goose <a href="/html/abbreviations.html#Dhanaṃj">Dhanaṃj.</a>
</meaning>


</entry>

<entry>
<word>
ḍhārikā </word>


<meaning>
{ḍhārikā} f. the julus <a href="/html/abbreviations.html#ĀpGṛ">ĀpGṛ.</a>,
</meaning>


</entry>

<entry>
<word>
ḍhāla </word>


<meaning>
{ḍhāla} n. 'a shield', See {lin}
</meaning>


</entry>

<entry>
<word>
 ḍhālin </word>


<meaning>
{ḍhālin} mfn. armed with a shield, Rudraj
</meaning>


</entry>

<entry>
<word>
ḍhiṇḍhiṇikā </word>


<meaning>
{ḍhiṇḍhiṇikā} See {ṭiṇṭiṇ}
</meaning>


</entry>

<entry>
<word>
ḍhuḍhi </word>


<meaning>
{ḍhuḍhi} vḷ. for {ḍhuṇḍhi}
</meaning>


</entry>

<entry>
<word>
ḍhuṇḍh </word>


<meaning>
{ḍhuṇḍh} (a Sautra root), to search
</meaning>


</entry>

<entry>
<word>
 ḍhuṇḍhana </word>


<meaning>
{ḍhuṇḍhana} n. searching, investigating <a href="/html/abbreviations.html#W">W.</a>
</meaning>


</entry>

<entry>
<word>
 ḍhuṇḍhi </word>


<meaning>
{ḍhuṇḍhi} m. N. of Gaṇêsa <a href="/html/abbreviations.html#KāśīKh">KāśīKh.</a>
</meaning>


</entry>

<entry>
<word>
 ḍhuṇḍhirāja </word>


<meaning>
{rāja} m. N. of the author of a work on nativities 
</meaning>


<meaning>
 of Bālakṛishna's father 
</meaning>


<meaning>
 of Vināyaka-bhaṭṭa's father (about 1800 AḌ.) 
</meaning>


<meaning>
 {jâkhyāna} n. N. of <a href="/html/abbreviations.html#GaṇP">GaṇP.</a> ii, 43
</meaning>


</entry>

<entry>
<word>
 ḍhuṇḍhikā </word>


<meaning>
{ḍhuṇḍhikā} f. a gloss (?)
</meaning>


</entry>

<entry>
<word>
 ḍhuṇḍhita </word>


<meaning>
{ḍhuṇḍhita} mfn. sought, inquired <a href="/html/abbreviations.html#W">W.</a>
</meaning>


</entry>

<entry>
<word>
ḍheṅka </word>


<meaning>
{ḍheṅka} m. N. of a bird <a href="/html/abbreviations.html#Vasantar">Vasantar.</a>viii, 12 
</meaning>


<meaning>
 ({ī}), f. a kind of dance
</meaning>


</entry>

<entry>
<word>
 ḍheṅkikā </word>


<meaning>
{ḍheṅkikā} f. (in music) a kind of measure 
</meaning>


<meaning>
 {tāla} m. id. 

</meaning>


</entry>

<entry>
<word>
ḍhevvukā </word>


<meaning>
{ḍhevvukā} f. a coin, Kathârn
</meaning>


</entry>

<entry>
<word>
ḍhorasamudra </word>


<meaning>
{ḍhora-samudra} N. of a locality <a href="/html/abbreviations.html#Romakas">Romakas.</a>
</meaning>


</entry>

<entry>
<word>
 ḍholāsamudra </word>


<meaning>
{ḍholā-samudra} = {ḍhora-s} <a href="/html/abbreviations.html#W">W.</a>
</meaning>


</entry>

<entry>
<word>
 ḍhola </word>


<meaning>
{ḍhola} m. a large drum, Rudraj
</meaning>


</entry>

<entry>
<word>
 ḍholasamudrikā </word>


<meaning>
{"ṣsamudrikā} f. 'coming from or growing in Ḍhola-samudra (- {ḍhora-s}), Leea macrophylla <a href="/html/abbreviations.html#L">L.</a>
</meaning>


</entry>

<entry>
<word>
ḍhollarī </word>


<meaning>
{ḍhollarī} f. a kind of composition
</meaning>


</entry>

<entry>
<word>
ḍhauk </word>


<meaning>
{ḍhauk} cl. 1. Ā. {kate} (pf. {ḍuḍhauke} [<a href="/html/abbreviations.html#Pāṇ">Pāṇ.</a> 7-4, 59 <a href="/html/abbreviations.html#Kāś">Kāś.</a>] <a href="/html/abbreviations.html#Hcar">Hcar.</a> <a href="/html/abbreviations.html#Bhaṭṭ">Bhaṭṭ.</a>), to approach (with acc.) <a href="/html/abbreviations.html#Kād">Kād.</a> <a href="/html/abbreviations.html#Hcar">Hcar.</a> <a href="/html/abbreviations.html#Bhaṭṭ">Bhaṭṭ.</a>: Caus. {ḍhaukayati} (aor. {aḍuḍhaukat} <a href="/html/abbreviations.html#Pāṇ">Pāṇ.</a> 7-4, 2 and 59 <a href="/html/abbreviations.html#Kāś">Kāś.</a>), to bring near (to, gen.), cause to come near, offer, to any one (dat.) <a href="/html/abbreviations.html#Kathās">Kathās.</a> <a href="/html/abbreviations.html#Rājat">Rājat.</a> <a href="/html/abbreviations.html#Bhaṭṭ">Bhaṭṭ.</a> <a href="/html/abbreviations.html#KātyŚr">KātyŚr.</a> <a href="/html/abbreviations.html#Sch">Sch.</a>: Desid. {ḍuḍkaukiṣate} <a href="/html/abbreviations.html#Pāṇ">Pāṇ.</a> 7-4, 59 and viii, 4, 54 <a href="/html/abbreviations.html#Kāś">Kāś.</a>: Intens. {ḍoḍhaukyate}, vii, 4, 82 <a href="/html/abbreviations.html#Vārtt">Vārtt.</a> 1 <a href="/html/abbreviations.html#Pat">Pat.</a> 
</meaning>


<meaning>
 cf. {upa}.,
</meaning>


</entry>

<entry>
<word>
 ḍhaukana </word>


<meaning>
{ḍhaukana} n. offering, present <a href="/html/abbreviations.html#Rājat">Rājat.</a> vi, 166 <a href="/html/abbreviations.html#Śatr">Śatr.</a> xiv <a href="/html/abbreviations.html#KātyŚr">KātyŚr.</a> <a href="/html/abbreviations.html#Sch">Sch.</a> 
</meaning>


<meaning>
 cf. {upa-}
</meaning>


</entry>

<entry>
<word>
 ḍhaukita </word>


<meaning>
{ḍhaukita} mfn. brought near <a href="/html/abbreviations.html#MBh">MBh.</a> xii, 4138.
</meaning>


</entry>

<entry>
<word>
 </word>


<meaning>
{}
</meaning>


</entry>

</root>
