=== eGangotri/indicTools/xml/dictionary.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>
<!ELEMENT em (#PCDATA)>
<!ELEMENT entry (word,meaning+)>
<!ELEMENT li (em)>
<!ELEMENT meaning (#PCDATA|a|em|ol|strong)*>
<!ELEMENT ol (li)>
<!ELEMENT root (entry+)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT word (#PCDATA)>

=== eGangotri/indicTools/xml/RRRR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "dictionary.dtd">
<root>

<entry>
<word>
ṝ 1</word>


<meaning>
{ṝ} the eighth vowel of the alphabet (the corresponding long vowel to {ṛ} and resembling the sound of {ri} in {marine}, but after labials more like {ru} 
</meaning>


<meaning>
 it generally only appears in some forms of nouns in {ṛ}, viz. in the gen. pl. of all genders, in the acc. pl. m. and f. and in nom. acc. and voc. pl. n.)
</meaning>


</entry>

<entry>
<word>
 ṝkāra </word>


<meaning>
{kāra} m. the letter or sound {ṝ} <a href="/html/abbreviations.html#TPrāt">TPrāt.</a>
</meaning>


</entry>

<entry>
<word>
ṝ 2</word>


<meaning>
{ṝ} ind. an interjection of terror <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a particle implying reproach 
</meaning>


<meaning>
 warding off <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a particle used at the beginning of a sentence <a href="/html/abbreviations.html#L">L.</a>
</meaning>


</entry>

<entry>
<word>
ṝ 3</word>


<meaning>
{ṝ} {ṝs} m. a Bhairava <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 a Dānava <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 f. the mother of the gods 
</meaning>


<meaning>
 of the demons <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 recollection 
</meaning>


<meaning>
 going, motion <a href="/html/abbreviations.html#L">L.</a> 
</meaning>


<meaning>
 n. a breast <a href="/html/abbreviations.html#L">L.</a>
</meaning>


</entry>

<entry>
<word>
ṝ 4</word>


<meaning>
{ṝ} for 4. {ṛ} q.v
</meaning>


</entry>

<entry>
<word>
 </word>


<meaning>
{}
</meaning>


</entry>

</root>
